import os
import sys
import inspect


currentdir = os.path.dirname(
    os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0, parentdir) 


from sensitivity_analysis.matlab_sensitivity_analysis import (
    PCEMatlabM, GPMatlabM, PCGPMatlabM)
from sensitivity_analysis.experiment_container import ExperimentContainer


class DataReader:
    def __init__(self, directory, target=6, SAmethod=PCEMatlabM(), datafiles_ids=range(1, 6)) -> None:
        self.directory = directory
        self.ids = datafiles_ids
        self.target = target
        self.SAmethod = SAmethod

    def run_all(self):
        print(f"[working with data in {self.directory};]")
        for id in self.ids:
            print(f"case #{id}:")
            self.run_case(id)
            print()

    def run_case(self, id):
        exp = ExperimentContainer().read_from_files(f'{self.directory}/Xmatrix{id}.txt', f'{self.directory}/ymatrix{id}.txt')
        # print('x.shape:', exp.x_mat.shape)
        if not exp: 
            raise RuntimeError('test files not found!')
        exp.target_params_count = self.target
        exp = self.SAmethod.run(exp)
        if exp.is_error:
            print(exp.result)
        else: 
            print(f"best params to optimize={exp.result}")


def main():
    methods = {
        'PCEMatlabM': PCEMatlabM(addr='10.193.88.211', port=9889),
        'GPMatlabM': GPMatlabM(addr='10.193.88.211', port=9889),
        'PCGPMatlabM': PCGPMatlabM(addr='10.193.88.211', port=9889),
    }
    test_dirs = [
        ('autogenerated_data', 1, range(1, 6)),
        # ('normal_data', 3, range(1, 4)),
        # ('high_dimension_data', 10, range(1, 11)),
        # ('one_run_data', 10, range(1, 11)),
        # ('1to89', 6, range(1, 6)),
        # ('2to89', 6, range(1, 6)), 
        # ('3to89', 6, range(1, 6)), # works ok
        # ('4to89', 6, range(1, 6)), 
    ]
    for test_dir, target, test_ids in test_dirs:
        for name, method in methods.items():
            print('\n\nMethod:', name)
            DataReader(test_dir, target=target, SAmethod=method, datafiles_ids=test_ids).run_all()


if __name__ == '__main__':
    main()
